### ISSUE TITLE
git tag releases and news items on release notes

### ISSUE THREAD

**Issue by sckott** [ropensci/spatsoc#8]
howdy. congrats on new ver. on cran. We'd like maintainers to make sure to git tag each cran version released, as well as put associated news items in the release notes associated with the git tag. See   https://ropensci.github.io/dev_guide/releasing.html#releasing-1 - Let know any questions.

**Comment by robitalec** [comment]
Thanks @sckott. This is great, not sure why I missed this! Any idea if I could go back in time and create old releases?

- [ ] most recent commit tagged with version
- [ ] release created
- [ ] CRAN dates added to NEWS (instead of relying on `pkgdown` for the site)
- [ ] (removed NEWS.md from build ignore)

**Comment by sckott** [comment]
thanks. yes, you can git tag old commits. 

if you look back through your git history on github or locally and find the commit sha associated with the cran version that you submitted, then add a git tag to that commit and then you can add the release notes. to git tag a specific commit you can do https://stackoverflow.com/a/23996957/1091766

**Comment by robitalec** [comment]
Perfect. Thanks, I'll go back and add all the previous releases.

**Comment by robitalec** [comment]
- [X] all previous releases added
